CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] NVARCHAR(50) NOT NULL UNIQUE, 
    [Email] NVARCHAR(70) NOT NULL UNIQUE,
    [Password] NVARCHAR(33) NOT NULL,
    [IsPremium] BIT NOT NULL DEFAULT 0,
    [Role] NVARCHAR(10) NULL,
    [TeamId] INT NULL,
    [AvatarUrl] NVARCHAR(256) NULL, 
    CONSTRAINT [UserTeam] FOREIGN KEY ([TeamId]) REFERENCES [Team]([Id]) ON DELETE SET NULL ON UPDATE SET NULL
,
)
